[package]
name = "katabasis-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
clap = { version = "4.5.23", features = ["derive"] }
manager = { path = "../manager" }
