[workspace]
resolver = "2"
members = ["katabasis-app/src-tauri", "katabasis-cli", "manager", "elevator" , "manager-core"]

[profile.release]
strip = true # Remove Debug Symbols
lto = true # Enable Link to Optimisations
panic = "abort"
codegen-units = 1
opt-level = "s"

[profile.dev.package.sqlx-macros]
opt-level = 3

[workspace.dependencies]
tokio = "1.42.0"
log = "0.4.27"
