[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
tokio = { version = "1.42.0", features = ["full"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "macros" ] }
thiserror = "2.0.8"
serde = { version = "1.0.216", features = ["derive"] }
chrono = { version = "0.4.39", features = ["serde"] }
uuid = { version = "1.11.0", features = ["v4"] }
dunce = "1.0.5"
reqwest = { version = "0.12.11", features = ["json"]}
serde_json = "1.0.133"
regex = "1.11.1"
steamlocate = "2.0.0"
bytes = "1.9.0"
lazy_static = "1.5.0"
zip = "2.2.2"
url = "2.5.4"
toml = "0.8.19"
