[package]
name = "elevator"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "sync", "macros", "signal"] }
tonic = "0.12"
prost = "0.13"
anyhow = "1.0.96"

[build-dependencies]
tonic-build = "0.12"

[features]
winAdmin = []
