name: CI

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.cargo
          ./target
        key: CI_CACHE
        fail-on-cache-miss: false

    - name: Build Manager
      run: cargo build --package manager

    - name: Test Manager
      run: cargo test --package manager
