name: CI

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "29.3"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Manager
      run: cargo build -p manager

    - name: Test Manager
      run: cargo test -p manager
