name: CI

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - run: rustup toolchain install stable --profile minimal --no-self-update

    - uses: Swatinem/rust-cache@v2.7.7
      with:
        workspaces: .

    - run: |
        cargo check
        cargo test
