name: CI

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2.7.7
      with:
        workspaces: .

    - name: Build Workspace
      run: cargo build -p manager

    - name: Test Workspace
      run: cargo test -p manager
